### ISSUE TITLE
`numpy==1.19`使用時の`import physbo`実行失敗

### ISSUE THREAD

**Issue by tyszw** [issp-center-dev/PHYSBO#48]
numpyのバージョン1.19を使用してphysboを使用したいのですが、`import physbo`でnumpyが原因のValueErrorが出てしまいます。
numpy 1.19でも動かせるように対応していただくことは可能でしょうか？
また、回避策などご存じでしたら、ご教示いただけますと幸いです。

### エラーの再現方法

1. python環境の作成
2. physbo, numpyのインストール
            ```
            pip3 install physbo==1.1.0 numpy==1.19.5
            ```
3. pythonスクリプト、或いはnotebookで`import physbo`を実行

### 想定される挙動

以下、1行目に`import physbo`があるpythonスクリプトを実行した際のエラーメッセージです。

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import physbo
  File "/home/yoshizawa/.pyenv/versions/miniconda3-4.2.12/envs/physbo_test/lib/python3.7/site-packages/physbo/__init__.py", line 1, in <module>
    from . import gp
  File "/home/yoshizawa/.pyenv/versions/miniconda3-4.2.12/envs/physbo_test/lib/python3.7/site-packages/physbo/gp/__init__.py", line 1, in <module>
    from . import cov
  File "/home/yoshizawa/.pyenv/versions/miniconda3-4.2.12/envs/physbo_test/lib/python3.7/site-packages/physbo/gp/cov/__init__.py", line 1, in <module>
    from .gauss import gauss
  File "/home/yoshizawa/.pyenv/versions/miniconda3-4.2.12/envs/physbo_test/lib/python3.7/site-packages/physbo/gp/cov/gauss.py", line 4, in <module>
    from ._src.enhance_gauss import grad_width64
  File "physbo/gp/cov/_src/enhance_gauss.pyx", line 1, in init physbo.gp.cov._src.enhance_gauss
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

### 実行環境

- OS: CentOS 7
- Python: 3.7.13
- physbo: 1.1.0
- numpy: 1.19.5
- scipy: 1.7.3

よろしくお願いいたします。

**Comment by yomichi** [comment]
（たぶん安定な）方法がわかったので修正しました。
なるべく早く修正版をリリースしますが、お急ぎの場合は develop ブランチのコードをご利用ください。

``` bash
git clone --branch develop https://github.com/issp-center-dev/physbo
python3 -m pip install ./physbo
```

**Comment by tyszw** [comment]
ご返信ありがとうございます。

develop ブランチのコードで動作確認ができました。
迅速に対応してくださりありがとうございました。
