### ISSUE TITLE
writeメソッドにおけるnp.take()のエラー 

### ISSUE THREAD

**Issue by yuki-asano** [issp-center-dev/PHYSBO#57]
### 概要
physboをinteractiveモードで実行しているのですが、
最後のactionを評価して結果をwriteする際に以下のエラーが生じるように思います。
再現コードを添付しておりますので、ご確認いただけますと幸いです。

- エラー文
```
Traceback (most recent call last):
  File "./test_error.py", line 40, in <module>
    main()
  File "./test_error.py", line 35, in main
    policy.write(next_action, result)
  File "/home/asano/.local/lib/python3.8/site-packages/physbo/search/discrete/policy.py", line 138, in write
    np.take(self.actions, local_index, mode="clip") == action
  File "<__array_function__ internals>", line 5, in take
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 194, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

- 再現コード
[candidates.csv](https://github.com/user-attachments/files/16596866/candidates.csv)
[results.csv](https://github.com/user-attachments/files/16596867/results.csv)
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import csv
import physbo
import pandas as pd
import numpy as np

def get_data_from_result_list(index):
    with open('./results.csv') as f:
        reader = csv.reader(f)
        l = [row for row in reader]

    return float(l[index+1][0])


def main():
    # dir setting
    candidates_path  = './candidates.csv'

    # load_dataset
    data = pd.read_csv(candidates_path)
    X = data.iloc[:,:-1].to_numpy()
    actions = list(data[data["y"] < np.inf].index)

    # generate policy
    policy = physbo.search.discrete.policy(X)

    # search
    for i in range(20):
        next_action = policy.random_search(max_num_probes=1)
        print(next_action[0])
        result = get_data_from_result_list(next_action[0])
        print(result)
        policy.write(next_action, result)
        physbo.search.utility.show_search_results(policy.history, 10)
        print(policy.actions)

if __name__ == '__main__':
    main()
```

### 修正案
- コード該当部
https://github.com/issp-center-dev/PHYSBO/blob/master/physbo/search/discrete/policy.py#L141-L145

- 案
残actionのリストが空（最後の一つの実行時）の場合は、np.take()をスキップする
```
 if self.actions != []:  # skip this for the last action                                            
            local_index = np.searchsorted(self.actions, action)
            local_index = local_index[
                np.take(self.actions, local_index, mode="clip") == action
            ]
            self.actions = self._delete_actions(local_index)
```

ご検討よろしくお願いいたします。

**Comment by k-yoshimi** [comment]
バグと改善案の提案をありがとうございます。
最終候補がなくなった場合の挙動について、修正するようにします。
修正後、issueで該当箇所を記載しますので、それまで少々お待ちいただければと思います。
よろしくお願いします。

**Comment by yomichi** [comment]
なおしました。 (#58)
develop ブランチにはいっています。

**Comment by yuki-asano** [comment]
ご対応ありがとうございます。

**Comment by yomichi** [comment]
2024/8に出したv2.0.1に入っているのでclose
